<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Product>LimitIO</Product>
    <Company>LimitIO Project</Company>
    <Copyright>Copyright (c) LimitIO contributors</Copyright>
    <Version Condition="'$(Version)' == ''">0.1.0</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsNotAsErrors>CS8618;CS8602;CS8604</WarningsNotAsErrors>
  </PropertyGroup>

</Project>
